{"_type": "game", "slug": "bioshock-infinite", "id": "3620", "name": "BioShock Infinite", "platforms": ["PC", "PlayStation 3", "Xbox 360"], "release_date": "2013-03-26", "developer": "Irrational Games", "publisher": "2K Games",  "image": "https://media.rawg.io/media/games/4be/4be6a6aace7050003c85dcee56df51be.jpg", "rating": 4.7, "summary": "BioShock Infinite is a first-person shooter game...", "tags": ["sci-fi", "story-driven", "steampunk"], "developers": ["Irrational Games"], "releaseDate": "2013-03-26", "stores": ["Steam", "PlayStation Store", "Xbox Store"]}

{"_type": "game", "slug": "", "id": "829", "name": "Dark Souls III", "platforms": ["PC", "PlayStation 4", "Xbox One"], "release_date": "2016-03-24", "developer": "FromSoftware, Inc.", "publisher": "Bandai Namco Entertainment", "image": "https://media.rawg.io/media/games/65c/65c97b8de112f1e617f25f5b8b598e2f.jpg", "rating": 4.8, "summary": "Dark Souls III is an action role-playing game...", "tags": ["dark-fantasy", "challenging", "multiplayer"], "developers": ["FromSoftware, Inc."], "releaseDate": "2016-03-24", "stores": ["Steam", "PlayStation Store", "Xbox Store"]}

{"_type": "game", "slug": "", "id": "106218", "name": "The Legend of Zelda: Breath of the Wild", "platforms": ["Nintendo Switch", "Wii U"], "release_date": "2017-03-03", "developer": "Nintendo EPD", "publisher": "Nintendo",  "image": "https://media.rawg.io/media/games/63a/63a5f5b20f7e9d36e63f7b3253f35e0e.jpg", "rating": 4.9, "summary": "The Legend of Zelda: Breath of the Wild is an action-adventure game...", "tags": ["open-world", "fantasy", "exploration"], "developers": ["Nintendo EPD"], "releaseDate": "2017-03-03", "stores": ["Nintendo eShop"]}

{"_type": "game", "slug": "", "id": "527", "name": "Overwatch", "platforms": ["PC", "PlayStation 4", "Xbox One", "Nintendo Switch"], "release_date": "2016-05-24", "developer": "Blizzard Entertainment", "publisher": "Blizzard Entertainment",  "image": "https://media.rawg.io/media/games/b39/b398b7af9d070cd840202df4bfc49a2f.jpg", "rating": 4.7, "summary": "Overwatch is a team-based first-person shooter game...", "tags": ["team-based", "multiplayer", "hero-shooter"], "developers": ["Blizzard Entertainment"], "releaseDate": "2016-05-24", "stores": ["Battle.net", "PlayStation Store", "Xbox Store", "Nintendo eShop"]}

{"_type":"game", "slug": "", "id":"3498","name":"Grand Theft Auto V","release_date":"2013-09-17","developer":"Rockstar North","publisher":"Rockstar Games", "image":"https://media.rawg.io/media/games/84d/84da2ac3fdfc6507807a1808595afb12.jpg","rating":4.7,"summary":"Grand Theft Auto V is an action-adventure game...","tags":["open-world","crime","sandbox"],"platforms":["PC","Xbox One","PlayStation 4","PlayStation 3","Xbox 360"],"stores":["Steam","PlayStation Store","Xbox Store"]}

{"_type":"game", "slug": "", "id":"3328","name":"The Witcher 3: Wild Hunt","developer":"CD Projekt Red","publisher":"CD Projekt", "image":"https://media.rawg.io/media/games/0d9/0d9d6fc76be0505c680541b8c78c0576.jpg","rating":4.9,"summary":"The Witcher 3: Wild Hunt is an action role-playing game...","tags":["fantasy","open-world","adventure"],"release_date":"2015-05-19","platforms":["PC","PlayStation 4","Xbox One","Nintendo Switch"],"stores":["Steam","PlayStation Store","Xbox Store","Nintendo eShop"]}

{"_type":"game", "slug": "", "id":"4118","name":"Red Dead Redemption 2","platforms":["PlayStation 4","Xbox One","PC","Google Stadia"],"release_date":"2018-10-26","developer":"Rockstar Studios","publisher":"Rockstar Games","image":"https://media.rawg.io/media/games/511/5118aff5091cb3efec399c808f8c598f.jpg","rating":4.8,"summary":"Red Dead Redemption 2 is an epic tale of life in America...","tags":["western","open-world","action"],"developers":["Rockstar Studios"],"releaseDate":"2018-10-26","stores":["PlayStation Store","Xbox Store","Rockstar Launcher"]}

{"_type":"game", "slug": "", "id":"5679","name":"The Elder Scrolls V: Skyrim","platforms":["PC","PlayStation 4","Xbox One","Nintendo Switch","PlayStation 3","Xbox 360"],"release_date":"2011-11-11","developer":"Bethesda Game Studios","publisher":"Bethesda Softworks","image":"https://media.rawg.io/media/games/148/148b9d7b4b3330ed13c88384d9b986f1.jpg","rating":4.6,"summary":"The Elder Scrolls V: Skyrim is an open-world action role-playing game...","tags":["fantasy","adventure","exploration"],"developers":["Bethesda Game Studios"],"releaseDate":"2011-11-11","stores":["Steam","PlayStation Store","Xbox Store","Nintendo eShop"]}

{"_type":"game", "slug": "", "id":"33214","name":"Minecraft","platforms":["PC","Xbox One","PlayStation 4","Nintendo Switch","Android","iOS","Xbox 360","PlayStation 3","PlayStation Vita","Wii U"],"release_date":"2011-11-18","developer":"Mojang Studios","publisher":"Mojang Studios","image":"https://media.rawg.io/media/games/325/325b5eb08c3f71f35151c42c9f8e078f.jpg","rating":4.5,"summary":"Minecraft is a sandbox survival game...","tags":["sandbox","adventure","creativity"],"developers":["Mojang Studios"],"releaseDate":"2011-11-18","stores":["Minecraft Official Website","Microsoft Store","PlayStation Store","Nintendo eShop"]}

{"_type":"game", "slug": "", "id":"3944","name":"Half-Life 2","platforms":["PC","Xbox","PlayStation 3"],"release_date":"2004-11-16","developer":"Valve Corporation","publisher":"Valve Corporation", "image":"https://media.rawg.io/media/games/82c/82c81b6db4bfc4e5beeb4ff7a158f38f.jpg","rating":4.9,"summary":"Half-Life 2 is a first-person shooter game...","tags":["sci-fi","story-rich","single-player"],"developers":["Valve Corporation"],"releaseDate":"2004-11-16","stores":["Steam","Xbox Store","PlayStation Store"]}

//update slug, hours played 'hours-played'

//b4fadc9b-035f-42e7-bac8-266e21d45296
//b4fadc9b-035f-42e7-bac8-266e21d45296



